version: '3.9'

services:
    # --- NestJS App ---
    api:
        build:
            context: .
            dockerfile: ./src/Dockerfile
            target: dev  # choose what u want
        container_name: nest-api
        restart: unless-stopped
        ports:
            - "8000:8000"
        env_file:
            - .env #unfortunately it's not here for u
        depends_on:
            - db
        networks:
            - backend

    # --- PostgreSQL Database ---
    db:
        image: postgres:15.1-alpine
        container_name: postgres-db
        restart: unless-stopped
        #replace it with yours
        environment:
            POSTGRES_DB: a
            POSTGRES_USER: b 
            POSTGRES_PASSWORD: c
        ports:
            - "5432:5432" #u dont have to expose it
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - backend

# --- volumes ---
volumes:
    pg_data:

# --- network ---
networks:
    backend:
